#!/usr/bin/env ruby
#
# Generate a random string and print it. Accepts an optional string length.

require 'base64'

string = ''

len = ARGV[0] ? ARGV[0].to_i : 8

len.times { string += (rand(74) + 48).chr }

puts [string].pack('m')[1,6]
